### ISSUE TITLE
Unhandled rejection TypeError: D:\blog\themes\brewski\layout\partial\nav.pug:6

### ISSUE THREAD

**Issue by javais** [tiaanduplessis/hexo-theme-brewski#1]
D:\blog>hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: D:\blog\themes\brewski\layout\partial\nav.pug:6
    4|             - var re = /^(http|https):\/\/*/gi;
    5|             - var tar = re.test(value) ? "_blank" : "_self"
  > 6|             - var type = value.indexOf('.html') === -1 ? 'no-barba' : ''
    7|             a.nav-list-link(href=url_for(value) target=tar class=type)
    8|                 != key.toUpperCase()
    9|

Cannot read property 'indexOf' of null
    at eval (eval at wrap (D:\blog\node_modules\_pug-runtime@2.0.0@pug-runtime\wrap.js:6:10), <anonymous>:88:17)
    at template (eval at wrap (D:\blog\node_modules\_pug-runtime@2.0.0@pug-runtime\wrap.js:6:10), <anonymous>:377:98)
    at _compiled (D:\blog\node_modules\_hexo@3.3.7@hexo\lib\theme\view.js:127:30)
    at View.render (D:\blog\node_modules\_hexo@3.3.7@hexo\lib\theme\view.js:29:15)
    at D:\blog\node_modules\_hexo@3.3.7@hexo\lib\hexo\index.js:390:25
    at tryCatcher (D:\blog\node_modules\_bluebird@3.5.0@bluebird\js\release\util.js:16:23)
    at D:\blog\node_modules\_bluebird@3.5.0@bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog\node_modules\_hexo@3.3.7@hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

INFO  Bye!

**Comment by shytab** [comment]
@fullstack-dev I also encountered this problem. Do you solve this ?

**Comment by shytab** [comment]
OK, for anyone else who have this problem:
change below code in layout/partial/nav.pug:
- var type = value.indexOf('.html') === -1 ? 'no-barba' : ''
into this:
- var type = value === null ? '' : (value.indexOf('.html') === -1 ? 'no-barba' : '')
